version: '3.3'

services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017

    comments:
        container_name: reviewzone_comments
        build: './comments'
        # ports:
        #     - 3000:3000
        volumes: 
            - ./comments:/go/src/github.com/minhajuddinkhan/reviewzone/comments

    dump:
        container_name: reviewzone_dump
        build: './dump'
        # ports:
        #     - 4000:4000
        volumes: 
            - ./dump:/go/src/github.com/minhajuddinkhan/reviewzone/dump
 
    reviewer:
        container_name: reviewzone_reviewer
        build: './reviewer'
        volumes: 
            - ./reviewer:/go/src/github.com/minhajuddinkhan/reviewzone/reviewer
        # ports:
        #     - 5000:5000

    api:
        build: '.'
        container_name: reviewzone_api
        volumes: 
            - ./api:/go/src/github.com/minhajuddinkhan/reviewzone/api
        depends_on:
            - comments
            - dump
            - reviewer
            - mongodb
        ports:
            - 6000:6000